HDT3213/godis

redis/parser/parser.go

`readLine` function could make sure that `msg` variable ends with `"\r\n"`. So, I think `str := strings.TrimSuffix(string(msg), "\n"); str = strings.TrimSuffix(str, "\r")` and `str := strings.TrimSuffix(string(msg), "\r\n")` have a same result, but the latter is better way.

optimize trimming suffix '\r\n' of string

---

lib/sync/wait/wait.go

Currently a non-buffer channel is used to control timeout processing, which means that if an event is not processed before the time expires, there will be no receiver for the channel. This causes the goroutine to block forever at the `c <- true` step, leading to goroutine leak. The above is also mentioned in issue  #30 .
We can verify the occurrence of the above scenario with the following code:
```go
func main() {
go func() {
for {
fmt.Printf("NumGoroutine = %d\n", runtime.NumGoroutine())
time.Sleep(time.Second)
}
}()
for {
work()
}
}
func work() {
w := Wait{}
defer w.Done()
w.Add(1)
w.WaitWithTimeout(100 * time.Microsecond)
}
```
Running the above code will result in the output:
```
NumGoroutine = 3
NumGoroutine = 68
NumGoroutine = 134
NumGoroutine = 199
NumGoroutine = 264
NumGoroutine …
```

fix: goroutine leak in Wait

---

transaction.go

当前DISCARD命令返回值为QUEUED，而Redis协议DISCARD的返回值为OK。
此处代码的返回值应该改为reply.MakeOkReply()

fix: fix the bug for DiscardMulti which returns wrong reply.

---

cluster/router.go
commands.md
database/hash.go
database/hash_test.go

This is a command added in Redis version 6.2.0.
Time complexity: O(N) where N is the number of fields returned
Usage:  HRANDFIELD key [ count [WITHVALUES]]
When called with just the key argument, return a random field from the hash value stored at key.
If the provided count argument is positive, return an array of distinct fields. The array's length is either count or the hash's number of fields (HLEN), whichever is lower.
If called with a negative count, the behavior changes and the command is allowed to return the same field multiple times. In this case, the number of returned fields is the absolute value of the specified count.
The optional WITHVALUES modifier changes the reply so it includes the respective values of the randomly selected hash fields.
Example(Using this PR version): …

Feat:Add hrandfield Command

---

cluster/router.go
commands.md
database/hash.go
database/hash_test.go
go.sum

This is a command that was updated in redis 3.2.0.
Time complexity: O(1).
Usage: hstrlen key field
Return
Integer reply: the string length of the value associated with field, or zero when field is not present in the hash or key does not exist at all.
Examples:
```
0.0.0.0:6399> hset testhash A 12345678
(integer) 1
0.0.0.0:6399> hstrlen testhash A
(integer) 8
0.0.0.0:6399> hstrlen non_exist_key A
(integer) 0
0.0.0.0:6399> hstrlen testhash non_exist_field
(integer) 0
```

Feat: add HStrlen command.

---

cluster/router.go
commands.md
database/string.go
database/string_test.go

Both commands are available in Redis 6.2.0.
GETEX:
Usage: GETEX key [ EX seconds | PX milliseconds | PERSIST]
Time complexity: O(1)
Get the value of key and optionally set its expiration. GETEX is similar to GET, but is a write command with additional options.
this command return the value of key, or nil when key does not exist,or an error if the key's value type isn't a string.
Options
The GETEX command supports a set of options that modify its behavior:
- EX seconds -- Set the specified expire time, in seconds.
- PX milliseconds -- Set the specified expire time, in milliseconds.
- PERSIST -- Remove the time to live associated with the key.
Note that there are two more additional options "EXAT" and "PXAT" in redis, but they are not yet supported here.
GETDEL:
Usage: GETDEL key
Time …

Feat: Add two string commands: "GETEX" and "GETDEL"

---

database/string.go

We only need the set command in AOF.
This is the GetSet implementation in redis.
```
void getsetCommand(client *c) {
if (getGenericCommand(c) == C_ERR) return;
c->argv[2] = tryObjectEncoding(c->argv[2]);
setKey(c,c->db,c->argv[1],c->argv[2],0);
notifyKeyspaceEvent(NOTIFY_STRING,"set",c->argv[1],c->db->id);
server.dirty++;
/* Propagate as SET command */
rewriteClientCommandArgument(c,0,shared.set);
}
```

Convert GETSET to SET command to write  AOF

---

cluster/copy.go
cluster/copy_test.go
cluster/router.go
cluster/utils.go
commands.md
database/cluster_helper.go
database/database.go
database/keys.go
database/keys_test.go

**COPY source destination [DB destination-db] [REPLACE]**
Available since: 6.2.0
Time complexity: O(N) worst case for collections, where N is the number of nested items. O(1) for string values.
This command copies the value stored at the source key to the destination key.
By default, the destination key is created in the logical database used by the connection. The DB option allows specifying an alternative logical database index for the destination key.
The command returns an error when the destination key already exists. The REPLACE option removes the destination key before copying the value to it.
Return
Integer reply, specifically:
1 if source was copied.
0 if source was not copied.
Above from https://redis.io/commands/copy/
Examples(By this pr version):
```
127.0.0.1:6399> keys * …
```

Feat:Add "copy" command

---

lib/timewheel/timewheel.go

1. add a struct to help 
```
// slot is pos, The etask is the element wrapped after the task inserts it into the list
// through this, can remove task in O(1)
type location struct {
slot  int
etask *list.Element
}
```
2.  modified the up one to the down one to avoid block other case in select.
```
func (tw *TimeWheel) tickHandler() {
l := tw.slots[tw.currentPos]
tw.scanAndRunTask(l)
if tw.currentPos == tw.slotNum-1 {
tw.currentPos = 0
} else {
tw.currentPos++
}
}
func (tw *TimeWheel) tickHandler() {
l := tw.slots[tw.currentPos]
if tw.currentPos == tw.slotNum-1 {
tw.currentPos = 0
} else {
tw.currentPos++
}
// start a goroutine
go tw.scanAndRunTask(l)
}
```

remove task O(1), and none block tickerHandler()

---

datastruct/dict/simple.go

Just a small bug which may cause IndexOutOfBound in some cases.
The break condition should be ```i == size```,  because ```result := make([]string, size)``` set the size of ```result``` as ```size```

Small bugfix on datastructure/dict/simple.go

---

lib/sync/wait/wait.go

perf: slightly optimize the channel type to save memory space in file lib/sync/wait/wait.go
Limited ability, hope to make it better~

perf: slightly optimize the channel type to save memory space in file lib/sync/wait/wait.go

---

config/config.go
redis/parser/parser.go

perf: slightly optimize config/config.go 
- Exclude the struct tag is space
- Exclude configuration file comment, which is starting with space
fix: in the case of panic unexpected happened in the method parse0 of parser/parser.go, closing of the channel is needed to prevent the program from getting stuck~
- fine-tune the coding of parser/parser.go
Limited ability, hope to make it better~

perf: slightly optimize config/config.go & fix: channel`s closing and refactor parser/parser.go

---

redis/server/server.go

perf: slightly optimize the value`s type of map to save memory space in file redis/server/server.go
Note: I'm not sure if setting the map\`s value to the int 1 is useful, but if the original purpose is using the dictionary as a "set" type, then I think it's the map`s value is "struct{}{}" better.
If my idea is incomplete, I will close this PR~ 
Have a nice day~
Limited ability, hope to make it better~

perf: slightly optimize the value`s type of map 

---

aof/aof.go

By the way, there is another alternative, using lambda function, which I didn't commit because it changed the style of the code,  if you prefer, I can submit it, as follows：
```golang
for p := range handler.aofChan {
func() {
handler.pausingAof.RLock() // prevent other goroutines from pausing aof
defer handler.pausingAof.RUnlock()
if p.dbIndex != handler.currentDB {
// 	select db
data := reply.MakeMultiBulkReply(utils.ToCmdLine("SELECT", strconv.Itoa(p.dbIndex))).ToBytes()
_, err := handler.aofFile.Write(data)
if err != nil {
logger.Warn(err)
return // skip this command
}
handler.currentDB = p.dbIndex
}
data := reply.MakeMultiBulkReply(p.cmdLine).ToBytes()
_, err := handler.aofFile.Write(data)
if err != nil {
logger.Warn(err)
}
}()
handler.aofFinished <- struct{}{}
}
```
Limited ability, …

fix: fix a deadlock issue caused by unclosing RUnlock

---

datastruct/dict/concurrent.go

This will ensure that count in ConcurrentDict is correct

addCount should only be executed when there is data insertion

---

datastruct/sortedset/skiplist.go

There is an exception in skiplist. We should convert the range of k from [1,17] to [1,16].

bugfix:convert the range of k from [1,17] to [1,16]

---

lib/geohash/geohash.go

geohash的长度是确定的，因此可以直接创建出geohash的切片。另外bytes.Buffer第一次会创建容量为64的byte silce，对于8Byte的geohash存在浪费。

Pre-allocate geohash slice memory

---

lib/geohash/geohash.go

geohash 切片预分配的长度计算存在问题，如果长度不是8的整数需要+1

fix geohash len error

---

database/string.go

fix: Add the write aof to the func execSetBit, the execSetBit is a write command, should be recorded

fix: string.go execSetBit did not record aof log

---

tcp/server.go

信号触发以后`errCh`这个channel就没有接收者了，继续使用`errCh <- err`导致阻塞，从而使服务无法退出。

bugfix: server stuck after signal received

---

redis/protocol/errors.go

the line 85 has some error
I change    
return "ERR Protocol error: '" + r.Msg -->
return "ERR Protocol error '" + r.Msg + "' command"
I think you may forget copy all the code.
It's a small error,I just change one line.

fix /redis/protocol/errors

---

datastruct/dict/concurrent_test.go
redis/protocol/errors.go

In func TestConcurrentForEach(t *testing.T)
the t.Error("remove test failed: expected " + expectedKey + ", actual: " + key)
forget to change the ’remove‘ -> ’forEach‘
Just a little change

fix concurrent_test.go t.Error

---

database/database.go
database/util_test.go
datastruct/dict/concurrent.go
datastruct/dict/concurrent_test.go
datastruct/lock/lock_map.go

1.Added `RWLocks` and `RWUnLocks` methods to `concurrent. go`, and replaced the `RWLocks` and `RWUnLocks` methods used in `database. go` with those implemented in `concurrent. go`. Replace the `Get`, `Put`, `PutIfAbsent`, `PutIfExists` and `Remove` methods of `concurrent. go` with methods that do not require locking, so executing the command **does not require locking twice.**
2.Added some test in `concurrent_test.go`.
3.`DB.locker` is now deprecated.

Modify the implementation of database RWLocks and RWUnLocks

---

database/set_test.go

I wonder that this was an little mistake because exec key1 for 2 times doesn't reach the purpose of test sinter here

Update set_test.go fix a little error

---

datastruct/list/quicklist.go

bugfix: Runtime error will happen in RemoveAllByVal() if iter.remove() removes quicklist's last page (it happens when last page has only one item) and the quicklist is not empty. In this case, iter.atEnd() will be false, which will cause a nil pointer dereference in RemoveAllByVal().
Solution: If iter.remove() remove last item, let it meet iter.atEnd() == true.

Fix bug in quicklist.go

---

datastruct/dict/concurrent.go
datastruct/dict/simple.go
datastruct/lock/lock_map.go
datastruct/sortedset/sortedset.go
tcp/echo_test.go
tcp/server.go

Modify  code comments and unnecessary type conversions

Modify  code comments and unnecessary type conversions

---

database/keys.go

The previous code calculated TTL directly by int64 / time.Second or int64 / time.Millisecond, which could result in a calculation error of up to 1s/1ms. Now, using math.Round ensures that TTL is rounded to the nearest whole second/millisecond, improving the accuracy of the calculation.

bugfix: Use rounding to calculate TTL

---

database/string.go

Fix the issue with the result format returned by the randomkey command.
```sh
127.0.0.1:6399> set k v
OK
127.0.0.1:6399> RANDOMKEY
"\"k\""
```
```sh
127.0.0.1:6399> set k v
OK
127.0.0.1:6399> RANDOMKEY
"k"
```

bugfix: Fix the issue with the result format returned by the randomkey command

---

database/hash.go
database/hash_test.go
database/keys.go
database/set.go
database/set_test.go
database/sortedset.go
database/sortedset_test.go
datastruct/dict/simple.go
datastruct/dict/simple_test.go
datastruct/set/set.go
datastruct/set/set_test.go
datastruct/sortedset/sortedset.go
datastruct/sortedset/sortedset_test.go

接 #225 
因为数据都存在`simple_dict`或`map`里，所以三个命令都是一次性返回全部。
可用于有GUI的客户端查看数据。

Add sscan, hscan, zscan

---

lib/timewheel/timewheel.go
lib/timewheel/timewheel_test.go

While removing a long list of items when they expire, godis fails because of concurrent use of map from following methods:
```go
github.com/hdt3213/godis/lib/timewheel.(*TimeWheel).removeTask(...)
github.com/hdt3213/godis/lib/timewheel.(*TimeWheel).scanAndRunTask.func1()
```
This PR is aimed to resolve this issue #233.
Error log is:
```
fatal error: concurrent map read and map write
goroutine 10 [running]:
github.com/hdt3213/godis/lib/timewheel.(*TimeWheel).removeTask(...)
/Users/erkan/go/pkg/mod/github.com/hdt3213/godis@v1.2.9/lib/timewheel/timewheel.go:170
github.com/hdt3213/godis/lib/timewheel.(*TimeWheel).start(0xc0000bcea0)
/Users/erkan/go/pkg/mod/github.com/hdt3213/godis@v1.2.9/lib/timewheel/timewheel.go:97 +0x1ae
created by github.com/hdt3213/godis/lib/timewheel.(*TimeWheel).Start …
```

added timewheel concurrency support

---

lib/logger/logger.go

Alllowing custom loggers for embedded godis service. By this PR, we can use any logger package properly.

logger.DefaultLogger as interface

---

lib/geohash/neighbor.go

在encode0方法中的每次循环，对于经度（对应 box[0][0] 和 box[0][1]）和纬度（对应 box[1][0] 和 box[1][1]）这两个维度，都是按照相同的逻辑去不断地二等分范围。
每一次循环迭代，都是通过计算当前维度范围的中间值 mid，然后根据坐标值与 mid 的比较结果来更新该维度范围的边界（也就是 box 中对应维度的两个值）。这种二等分的更新方式是完全对称的操作，在经过相同次数的迭代（由 bitSize 决定迭代次数）后，经度和纬度这两个维度的范围缩小比例是一样的，所以最终它们的范围差值（也就是 box[0][1] - box[0][0] 和 box[1][1] - box[1][0]）会相同，即height和width相同。
由于后续内容对于height和width的使用是对称的，尽管逻辑与正常的经纬度计算逻辑不一致，但是并不影响最终结果。

fix issue #238

---

cluster/commands/del.go
cluster/core/tcc.go

1. cluster del 这里的操作会导致发给其他节点的 del 命令最后多出一个 nil，貌似是没有必要的
2. 优化了一下 tcc 中的代码

optimize del in cluster
