HDT3213/godis

- src/db/string.go
set 时
如果设置了ttl 则以最新的ttl为准
如果没有设置ttl 且数据新增数据的，不设置过期时间。
> 对set时过期时间策略的修改

- datastruct/dict/concurrent.go
- datastruct/dict/concurrent_test.go
ConcurrentDict 执行 Remove 之后 count值没有对应的减少
> ConcurrentDict Remove add decreaseCount

- datastruct/list/linked.go
> optimize logic of linkedlist

- lib/wildcard/wildcard.go
- lib/wildcard/wildcard_test.go
see [keys](https://redis.io/commands/keys)
> fix: keys rang match & negative match

- lib/logger/files.go
- lib/logger/logger.go
Limited ability, hope to make it better~
> refactor: fine-tune the coding of lib/logger/

- lib/utils/rand_string.go
fix: uses the provided seed value to initialize the function rand, for fixing the generation of the same rand string in the case of multiple executions.
Have a nice day~
Limited ability, make it better~
> fix: uses the provided seed value to initialize the function rand

- datastruct/dict/concurrent.go
- shorten the lock time of concurrent.go`s function "Put"
- slightly optimize the value\`s type of map concurrent.go\`s function "RandomDistinctKeys" & avoid duplicate input the same map`s key
If you see it today, the have a nice day again ~
Limited ability, make it better~
> perf: shorten lock time & optimize map`s value type & fix random num

- datastruct/dict/concurrent.go
- the name of the variable "shard" has been defined, and change variable "shard" `s name in the function to avoid the case of "Variable Shadowing"
- remove unnecessary type conversion "uint32(hashCode)"
Have a nice day~
Limited ability, make it better~
> refactor: fix variable names & remove unnecessary type conversion

- datastruct/sortedset/sortedset.go
- datastruct/sortedset/sortedset_test.go
Fixed the error caused by incorrect "boder" pass value. And added a simple unit test to verify correctness.
> Bug fix : ZPOPMIN command.

- database/replication.go
- redis/connection/conn.go
- redis/server/server.go
- pooled connection: reduce the pressure on the GC to process heap memory objects with high concurrent "connection" in the file redis/connection/conn.go
Have a nice day~
Limited ability, make it better~
> perf: pooled connection`s instantiation

- tcp/server.go
发现ListenAndServe退出的地方，因为在两个go里执行close，所以如果是收到退出signal，"listener.Close()和handler.Close()"会执行两遍，虽然不会出什么重要的问题，但是感觉可以稍微改进一点点
> server exit gracefully a bit

- cluster/router.go
- database/keys.go
- database/keys_test.go
> ADD EXPIRETIME and EXPIRETIME command

- database/list_test.go
List_test.go func TestPush an unexpected line made the test went wrong.
And 4 commits merged into single one now
> Fix list_test.go func TestPush #140 merged into one commit

- config/config.go
- database/server.go
- database/systemcmd.go
- database/systemcmd_test.go
- main.go
- Add info command
- Generate a new runid for each start of godis
> Add info command

- cluster/router.go
- cluster/utils.go
- database/string.go
- database/string_test.go
> Add randomkey command

- database/server.go
if appendonly is no,the Persister will no be create,the pausingAof is nil
> bug fix:RewriteAof will panic if appendonly property is no

- tcp/server.go
Update server.go revise redundant line of annotation
> Update server.go revise redundant line of annotation

- database/sortedset_test.go
there is a useless line in func TestRangeByScore
> Update sortedset_test.go delete line of useless

- cluster/cluster.go
- commands.md
- database/server.go
- database/systemcmd.go
- database/systemcmd_test.go
> add dbsize command

- redis/parser/parser.go
学习大佬代码的时候发现有个err没有处理，请问这个值得合并嘛😁
> update: 解析RDB格式错误处理

- database/hash.go
修复 field 不存在时 HIncrByFloat 没有追加 aof 的 bug
> fix bug of command HIncrByFloat

- database/list.go
- database/list_test.go
> support count of LPop and RPop
